"""rename User.role manager to member

Sprint 4 / role enforcement (#63 follow-up). Aligns the OAuth-side
``User.role`` column with the embedded-mode contract enum
``admin | member | viewer`` (see
``docs/integration/embedded-mode-identity-contract.md``). Pre-rename,
``manager`` was the operational-write role; the contract calls the
same concept ``member``. Single canonical name across the codebase.

Revision ID: 8407a32e9b07
Revises: e9f8a7ce4e46
Create Date: 2026-05-07 10:00:52.591519

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8407a32e9b07"
down_revision: str | Sequence[str] | None = ("102ce62707b9", "o6p7q8r9s0t1")
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Migrate ``users.role`` from the legacy enum to the canonical one.

    Three steps in one transaction:
    1. Drop the existing CHECK constraint that hard-codes ``manager``.
    2. Rename every row's ``manager`` → ``member``.
    3. Add a new CHECK constraint pinning the canonical enum
       ``admin | member | viewer`` (matched by ``models.py``).

    The original constraint may have been auto-named or explicit; we
    look it up by querying ``pg_constraint`` for any CHECK on the
    ``users.role`` column — auto-named constraints from PR-history vary.
    """
    # Drop any pre-existing CHECK constraint on users.role. We don't
    # know its name (auto-generated by Postgres or explicit per
    # checkout), so query the catalog and drop by discovered name.
    bind = op.get_bind()
    bind.execute(
        sa.text(
            """
            DO $$
            DECLARE
                con_name text;
            BEGIN
                FOR con_name IN
                    SELECT con.conname
                    FROM pg_constraint con
                    JOIN pg_class rel ON rel.oid = con.conrelid
                    WHERE rel.relname = 'users'
                      AND con.contype = 'c'
                      AND pg_get_constraintdef(con.oid) ILIKE '%role%manager%'
                LOOP
                    EXECUTE format('ALTER TABLE users DROP CONSTRAINT %I', con_name);
                END LOOP;
            END $$;
            """
        )
    )

    # Migrate the rows.
    op.execute("UPDATE users SET role = 'member' WHERE role = 'manager'")

    # Drop any pre-existing constraint with our target name (defensive —
    # a fresh dev DB initialized from ``database_schema.py`` post-rename
    # may already have a ``ck_users_role`` constraint, which would
    # collide with the create below).
    bind.execute(sa.text("ALTER TABLE users DROP CONSTRAINT IF EXISTS ck_users_role"))

    # Pin the canonical enum.
    op.create_check_constraint(
        "ck_users_role",
        "users",
        "role IN ('admin', 'member', 'viewer')",
    )


def downgrade() -> None:
    """Revert to the legacy enum.

    Drops the canonical CHECK, maps ``member`` back to ``manager``,
    re-adds a CHECK pinning the legacy enum. ``member`` rows written
    *after* the upgrade are assumed to have come from the migration —
    if you've added a feature that writes ``member`` for a different
    reason, this downgrade will conflate them.
    """
    op.drop_constraint("ck_users_role", "users", type_="check")
    op.execute("UPDATE users SET role = 'manager' WHERE role = 'member'")
    op.create_check_constraint(
        "ck_users_role",
        "users",
        "role IN ('admin', 'manager', 'viewer')",
    )
