# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_product_json.json
#   schema_hash: 5a1c337809d1

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class PropertyId(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9_]+$")]


class PropertyTag(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9_]+$")]


class PublisherProperty(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    publisher_domain: Annotated[
        str,
        Field(
            description="Domain where publisher's adagents.json is hosted (e.g., 'cnn.com')",
            pattern="^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$",
        ),
    ]
    property_ids: Annotated[
        list[PropertyId] | None,
        Field(
            description="Specific property IDs from the publisher's adagents.json. Mutually exclusive with property_tags.",
            min_length=1,
        ),
    ] = None
    property_tags: Annotated[
        list[PropertyTag] | None,
        Field(
            description="Property tags from the publisher's adagents.json. Product covers all properties with these tags. Mutually exclusive with property_ids.",
            min_length=1,
        ),
    ] = None


class FormatId(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    agent_url: Annotated[
        AnyUrl,
        Field(
            description="URL of the agent that defines this format (e.g., 'https://creatives.adcontextprotocol.org' for standard formats, or 'https://publisher.com/.well-known/adcp/sales' for custom formats)"
        ),
    ]
    id: Annotated[
        str,
        Field(
            description="Format identifier within the agent's namespace (e.g., 'display_300x250', 'video_standard_30s')",
            pattern="^[a-zA-Z0-9_-]+$",
        ),
    ]


class Placement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    placement_id: Annotated[str, Field(description="Unique identifier for the placement within the product")]
    name: Annotated[
        str, Field(description="Human-readable name for the placement (e.g., 'Homepage Banner', 'Article Sidebar')")
    ]
    description: Annotated[
        str | None, Field(description="Detailed description of where and how the placement appears")
    ] = None
    format_ids: Annotated[
        list[Any] | None,
        Field(
            description="Format IDs supported by this specific placement (subset of product's formats)", min_length=1
        ),
    ] = None


class DeliveryType(Enum):
    guaranteed = "guaranteed"
    non_guaranteed = "non_guaranteed"


class PricingOptions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pricing_option_id: Annotated[
        str,
        Field(description="Unique identifier for this pricing option within the product (e.g., 'cpm_usd_guaranteed')"),
    ]
    pricing_model: Annotated[Literal["cpm"], Field(description="Cost per 1,000 impressions")]
    rate: Annotated[float, Field(description="Fixed CPM rate (cost per 1,000 impressions)", ge=0.0)]
    currency: Annotated[
        str, Field(description="ISO 4217 currency code", examples=["USD", "EUR", "GBP", "JPY"], pattern="^[A-Z]{3}$")
    ]
    min_spend_per_package: Annotated[
        float | None,
        Field(
            description="Minimum spend requirement per package using this pricing option, in the specified currency",
            ge=0.0,
        ),
    ] = None


class PriceGuidance(BaseModel):
    floor: Annotated[
        float, Field(description="Minimum bid price - publisher will reject bids under this value", ge=0.0)
    ]
    p25: Annotated[float | None, Field(description="25th percentile winning price", ge=0.0)] = None
    p50: Annotated[float | None, Field(description="Median winning price", ge=0.0)] = None
    p75: Annotated[float | None, Field(description="75th percentile winning price", ge=0.0)] = None
    p90: Annotated[float | None, Field(description="90th percentile winning price", ge=0.0)] = None


class PricingOptions1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pricing_option_id: Annotated[
        str, Field(description="Unique identifier for this pricing option within the product (e.g., 'cpm_usd_auction')")
    ]
    pricing_model: Annotated[Literal["cpm"], Field(description="Cost per 1,000 impressions")]
    currency: Annotated[
        str, Field(description="ISO 4217 currency code", examples=["USD", "EUR", "GBP", "JPY"], pattern="^[A-Z]{3}$")
    ]
    price_guidance: Annotated[PriceGuidance, Field(description="Pricing guidance for auction-based CPM bidding")]
    min_spend_per_package: Annotated[
        float | None,
        Field(
            description="Minimum spend requirement per package using this pricing option, in the specified currency",
            ge=0.0,
        ),
    ] = None


class PricingOptions2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pricing_option_id: Annotated[
        str,
        Field(description="Unique identifier for this pricing option within the product (e.g., 'vcpm_usd_guaranteed')"),
    ]
    pricing_model: Annotated[Literal["vcpm"], Field(description="Cost per 1,000 viewable impressions (MRC standard)")]
    rate: Annotated[float, Field(description="Fixed vCPM rate (cost per 1,000 viewable impressions)", ge=0.0)]
    currency: Annotated[
        str, Field(description="ISO 4217 currency code", examples=["USD", "EUR", "GBP", "JPY"], pattern="^[A-Z]{3}$")
    ]
    min_spend_per_package: Annotated[
        float | None,
        Field(
            description="Minimum spend requirement per package using this pricing option, in the specified currency",
            ge=0.0,
        ),
    ] = None


class PriceGuidance3(BaseModel):
    floor: Annotated[float, Field(description="Minimum acceptable bid price", ge=0.0)]
    p25: Annotated[float | None, Field(description="25th percentile of recent winning bids", ge=0.0)] = None
    p50: Annotated[float | None, Field(description="Median of recent winning bids", ge=0.0)] = None
    p75: Annotated[float | None, Field(description="75th percentile of recent winning bids", ge=0.0)] = None
    p90: Annotated[float | None, Field(description="90th percentile of recent winning bids", ge=0.0)] = None


class PricingOptions3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pricing_option_id: Annotated[
        str,
        Field(description="Unique identifier for this pricing option within the product (e.g., 'vcpm_usd_auction')"),
    ]
    pricing_model: Annotated[Literal["vcpm"], Field(description="Cost per 1,000 viewable impressions (MRC standard)")]
    currency: Annotated[
        str, Field(description="ISO 4217 currency code", examples=["USD", "EUR", "GBP", "JPY"], pattern="^[A-Z]{3}$")
    ]
    price_guidance: Annotated[PriceGuidance3, Field(description="Statistical guidance for auction pricing")]
    min_spend_per_package: Annotated[
        float | None,
        Field(
            description="Minimum spend requirement per package using this pricing option, in the specified currency",
            ge=0.0,
        ),
    ] = None


class PricingOptions4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pricing_option_id: Annotated[
        str, Field(description="Unique identifier for this pricing option within the product (e.g., 'cpc_usd_fixed')")
    ]
    pricing_model: Annotated[Literal["cpc"], Field(description="Cost per click")]
    rate: Annotated[float, Field(description="Fixed CPC rate (cost per click)", ge=0.0)]
    currency: Annotated[
        str, Field(description="ISO 4217 currency code", examples=["USD", "EUR", "GBP", "JPY"], pattern="^[A-Z]{3}$")
    ]
    min_spend_per_package: Annotated[
        float | None,
        Field(
            description="Minimum spend requirement per package using this pricing option, in the specified currency",
            ge=0.0,
        ),
    ] = None


class PricingOptions5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pricing_option_id: Annotated[
        str,
        Field(description="Unique identifier for this pricing option within the product (e.g., 'cpcv_usd_guaranteed')"),
    ]
    pricing_model: Annotated[Literal["cpcv"], Field(description="Cost per completed view (100% completion)")]
    rate: Annotated[float, Field(description="Fixed CPCV rate (cost per 100% completion)", ge=0.0)]
    currency: Annotated[
        str, Field(description="ISO 4217 currency code", examples=["USD", "EUR", "GBP", "JPY"], pattern="^[A-Z]{3}$")
    ]
    min_spend_per_package: Annotated[
        float | None,
        Field(
            description="Minimum spend requirement per package using this pricing option, in the specified currency",
            ge=0.0,
        ),
    ] = None


class ViewThreshold(RootModel[float]):
    root: Annotated[
        float,
        Field(
            description="Percentage completion threshold for CPV pricing (0.0 to 1.0, e.g., 0.5 = 50% completion)",
            ge=0.0,
            le=1.0,
        ),
    ]


class ViewThreshold3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    duration_seconds: Annotated[
        int, Field(description="Seconds of viewing required (e.g., 30 for YouTube-style '30 seconds = view')", ge=1)
    ]


class Parameters(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    view_threshold: ViewThreshold | ViewThreshold3


class PricingOptions6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pricing_option_id: Annotated[
        str, Field(description="Unique identifier for this pricing option within the product (e.g., 'cpv_usd_50pct')")
    ]
    pricing_model: Annotated[Literal["cpv"], Field(description="Cost per view at threshold")]
    rate: Annotated[float, Field(description="Fixed CPV rate (cost per view)", ge=0.0)]
    currency: Annotated[
        str, Field(description="ISO 4217 currency code", examples=["USD", "EUR", "GBP", "JPY"], pattern="^[A-Z]{3}$")
    ]
    parameters: Annotated[Parameters, Field(description="CPV-specific parameters defining the view threshold")]
    min_spend_per_package: Annotated[
        float | None,
        Field(
            description="Minimum spend requirement per package using this pricing option, in the specified currency",
            ge=0.0,
        ),
    ] = None


class Parameters4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    demographic: Annotated[
        str,
        Field(
            description="Target demographic in Nielsen format: P/M/W/A/C + age range. Examples: P18-49 (Persons 18-49), M25-54 (Men 25-54), W35+ (Women 35+), A18-34 (Adults 18-34), C2-11 (Children 2-11)",
            pattern="^[PMWAC][0-9]{2}(-[0-9]{2}|\\+)$",
        ),
    ]
    min_points: Annotated[
        float | None, Field(description="Minimum GRPs/TRPs required for this pricing option", ge=0.0)
    ] = None


class PricingOptions7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pricing_option_id: Annotated[
        str, Field(description="Unique identifier for this pricing option within the product (e.g., 'cpp_usd_p18-49')")
    ]
    pricing_model: Annotated[Literal["cpp"], Field(description="Cost per Gross Rating Point")]
    rate: Annotated[float, Field(description="Fixed CPP rate (cost per rating point)", ge=0.0)]
    currency: Annotated[
        str, Field(description="ISO 4217 currency code", examples=["USD", "EUR", "GBP", "JPY"], pattern="^[A-Z]{3}$")
    ]
    parameters: Annotated[
        Parameters4, Field(description="CPP-specific parameters for demographic targeting and GRP requirements")
    ]
    min_spend_per_package: Annotated[
        float | None,
        Field(
            description="Minimum spend requirement per package using this pricing option, in the specified currency",
            ge=0.0,
        ),
    ] = None


class Parameters5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    duration_hours: Annotated[
        float | None, Field(description="Duration in hours for time-based flat rate pricing (DOOH)", ge=0.0)
    ] = None
    sov_percentage: Annotated[
        float | None, Field(description="Guaranteed share of voice as percentage (DOOH, 0-100)", ge=0.0, le=100.0)
    ] = None
    loop_duration_seconds: Annotated[
        int | None, Field(description="Duration of ad loop rotation in seconds (DOOH)", ge=1)
    ] = None
    min_plays_per_hour: Annotated[
        int | None, Field(description="Minimum number of times ad plays per hour (DOOH frequency guarantee)", ge=0)
    ] = None
    venue_package: Annotated[
        str | None,
        Field(
            description="Named venue package identifier for DOOH (e.g., 'times_square_network', 'airport_terminals')"
        ),
    ] = None
    estimated_impressions: Annotated[
        int | None,
        Field(
            description="Estimated impressions for this flat rate option (informational, commonly used with SOV or time-based DOOH)",
            ge=0,
        ),
    ] = None
    daypart: Annotated[
        str | None,
        Field(
            description="Specific daypart for time-based pricing (e.g., 'morning_commute', 'evening_prime', 'overnight')"
        ),
    ] = None


class PricingOptions8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pricing_option_id: Annotated[
        str,
        Field(
            description="Unique identifier for this pricing option within the product (e.g., 'flat_rate_usd_24h_takeover')"
        ),
    ]
    pricing_model: Annotated[Literal["flat_rate"], Field(description="Fixed cost regardless of delivery volume")]
    rate: Annotated[float, Field(description="Flat rate cost", ge=0.0)]
    currency: Annotated[
        str, Field(description="ISO 4217 currency code", examples=["USD", "EUR", "GBP", "JPY"], pattern="^[A-Z]{3}$")
    ]
    is_fixed: Annotated[
        Literal[True], Field(description="Whether this is a fixed rate (true) or auction-based (false)")
    ]
    parameters: Annotated[
        Parameters5 | None, Field(description="Flat rate parameters for DOOH and time-based campaigns")
    ] = None
    min_spend_per_package: Annotated[
        float | None,
        Field(
            description="Minimum spend requirement per package using this pricing option, in the specified currency",
            ge=0.0,
        ),
    ] = None


class Measurement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[
        str, Field(description="Type of measurement", examples=["incremental_sales_lift", "brand_lift", "foot_traffic"])
    ]
    attribution: Annotated[
        str, Field(description="Attribution methodology", examples=["deterministic_purchase", "probabilistic"])
    ]
    window: Annotated[str | None, Field(description="Attribution window", examples=["30_days", "7_days"])] = None
    reporting: Annotated[
        str, Field(description="Reporting frequency and format", examples=["weekly_dashboard", "real_time_api"])
    ]


class DeliveryMeasurement(BaseModel):
    provider: Annotated[
        str,
        Field(
            description="Measurement provider(s) used for this product (e.g., 'Google Ad Manager with IAS viewability', 'Nielsen DAR', 'Geopath for DOOH impressions')"
        ),
    ]
    notes: Annotated[
        str | None,
        Field(
            description="Additional details about measurement methodology in plain language (e.g., 'MRC-accredited viewability. 50% in-view for 1s display / 2s video', 'Panel-based demographic measurement updated monthly')"
        ),
    ] = None


class AvailableReportingFrequency(Enum):
    hourly = "hourly"
    daily = "daily"
    monthly = "monthly"


class AvailableMetric(Enum):
    impressions = "impressions"
    spend = "spend"
    clicks = "clicks"
    ctr = "ctr"
    video_completions = "video_completions"
    completion_rate = "completion_rate"
    conversions = "conversions"
    viewability = "viewability"
    engagement_rate = "engagement_rate"


class ReportingCapabilities(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    available_reporting_frequencies: Annotated[
        list[AvailableReportingFrequency], Field(description="Supported reporting frequency options", min_length=1)
    ]
    expected_delay_minutes: Annotated[
        int,
        Field(
            description="Expected delay in minutes before reporting data becomes available (e.g., 240 for 4-hour delay)",
            examples=[240, 300, 1440],
            ge=0,
        ),
    ]
    timezone: Annotated[
        str,
        Field(
            description="Timezone for reporting periods. Use 'UTC' or IANA timezone (e.g., 'America/New_York'). Critical for daily/monthly frequency alignment.",
            examples=["UTC", "America/New_York", "Europe/London", "America/Los_Angeles"],
        ),
    ]
    supports_webhooks: Annotated[
        bool, Field(description="Whether this product supports webhook-based reporting notifications")
    ]
    available_metrics: Annotated[
        list[AvailableMetric],
        Field(
            description="Metrics available in reporting. Impressions and spend are always implicitly included.",
            examples=[["impressions", "spend", "clicks", "video_completions"], ["impressions", "spend", "conversions"]],
        ),
    ]


class CoBranding(Enum):
    required = "required"
    optional = "optional"
    none = "none"


class LandingPage(Enum):
    any = "any"
    retailer_site_only = "retailer_site_only"
    must_include_retailer = "must_include_retailer"


class CreativePolicy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    co_branding: Annotated[CoBranding, Field(description="Co-branding requirement")]
    landing_page: Annotated[LandingPage, Field(description="Landing page requirements")]
    templates_available: Annotated[bool, Field(description="Whether creative templates are provided")]


class ProductCard(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format_id: Annotated[Any, Field(description="Circular reference to /schemas/v1/core/format-id.json")]
    manifest: Annotated[
        dict[str, Any], Field(description="Asset manifest for rendering the card, structure defined by the format")
    ]


class ProductCardDetailed(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format_id: Annotated[Any, Field(description="Circular reference to /schemas/v1/core/format-id.json")]
    manifest: Annotated[
        dict[str, Any],
        Field(description="Asset manifest for rendering the detailed card, structure defined by the format"),
    ]


class Product(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    product_id: Annotated[str, Field(description="Unique identifier for the product")]
    name: Annotated[str, Field(description="Human-readable product name")]
    description: Annotated[str, Field(description="Detailed description of the product and its inventory")]
    publisher_properties: Annotated[
        list[PublisherProperty],
        Field(
            description="Publisher properties covered by this product. Buyers fetch actual property definitions from each publisher's adagents.json and validate agent authorization.",
            min_length=1,
        ),
    ]
    format_ids: Annotated[
        list[FormatId],
        Field(
            description="Array of supported creative format IDs - structured format_id objects with agent_url and id"
        ),
    ]
    placements: Annotated[
        list[Placement] | None,
        Field(
            description="Optional array of specific placements within this product. When provided, buyers can target specific placements when assigning creatives.",
            min_length=1,
        ),
    ] = None
    delivery_type: Annotated[DeliveryType, Field(description="Type of inventory delivery", title="Delivery Type")]
    pricing_options: Annotated[
        list[
            PricingOptions
            | PricingOptions1
            | PricingOptions2
            | PricingOptions3
            | PricingOptions4
            | PricingOptions5
            | PricingOptions6
            | PricingOptions7
            | PricingOptions8
        ],
        Field(description="Available pricing models for this product", min_length=1),
    ]
    estimated_exposures: Annotated[
        int | None, Field(description="Estimated exposures/impressions for guaranteed products", ge=0)
    ] = None
    measurement: Annotated[
        Measurement | None, Field(description="Measurement capabilities included with a product", title="Measurement")
    ] = None
    delivery_measurement: Annotated[
        DeliveryMeasurement,
        Field(
            description="Measurement provider and methodology for delivery metrics. The buyer accepts the declared provider as the source of truth for the buy. REQUIRED for all products."
        ),
    ]
    reporting_capabilities: Annotated[
        ReportingCapabilities | None,
        Field(description="Reporting capabilities available for a product", title="Reporting Capabilities"),
    ] = None
    creative_policy: Annotated[
        CreativePolicy | None,
        Field(description="Creative requirements and restrictions for a product", title="Creative Policy"),
    ] = None
    is_custom: Annotated[bool | None, Field(description="Whether this is a custom product")] = None
    brief_relevance: Annotated[
        str | None,
        Field(description="Explanation of why this product matches the brief (only included when brief is provided)"),
    ] = None
    expires_at: Annotated[AwareDatetime | None, Field(description="Expiration timestamp for custom products")] = None
    product_card: Annotated[
        ProductCard | None,
        Field(
            description="Optional standard visual card (300x400px) for displaying this product in user interfaces. Can be rendered via preview_creative or pre-generated."
        ),
    ] = None
    product_card_detailed: Annotated[
        ProductCardDetailed | None,
        Field(
            description="Optional detailed card with carousel and full specifications. Provides rich product presentation similar to media kit pages."
        ),
    ] = None
