# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_performance-feedback_json.json
#   source_etag: W/"68ff4038-b32"
#   source_last_modified: Mon, 27 Oct 2025 09:49:44 GMT

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class MeasurementPeriod(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start: Annotated[AwareDatetime, Field(description="ISO 8601 start timestamp for measurement period")]
    end: Annotated[AwareDatetime, Field(description="ISO 8601 end timestamp for measurement period")]


class MetricType(Enum):
    overall_performance = "overall_performance"
    conversion_rate = "conversion_rate"
    brand_lift = "brand_lift"
    click_through_rate = "click_through_rate"
    completion_rate = "completion_rate"
    viewability = "viewability"
    brand_safety = "brand_safety"
    cost_efficiency = "cost_efficiency"


class FeedbackSource(Enum):
    buyer_attribution = "buyer_attribution"
    third_party_measurement = "third_party_measurement"
    platform_analytics = "platform_analytics"
    verification_partner = "verification_partner"


class Status(Enum):
    accepted = "accepted"
    queued = "queued"
    applied = "applied"
    rejected = "rejected"


class PerformanceFeedback(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    feedback_id: Annotated[str, Field(description="Unique identifier for this performance feedback submission")]
    media_buy_id: Annotated[str, Field(description="Publisher's media buy identifier")]
    package_id: Annotated[
        str | None, Field(description="Specific package within the media buy (if feedback is package-specific)")
    ] = None
    creative_id: Annotated[
        str | None, Field(description="Specific creative asset (if feedback is creative-specific)")
    ] = None
    measurement_period: Annotated[MeasurementPeriod, Field(description="Time period for performance measurement")]
    performance_index: Annotated[
        float,
        Field(
            description="Normalized performance score (0.0 = no value, 1.0 = expected, >1.0 = above expected)", ge=0.0
        ),
    ]
    metric_type: Annotated[MetricType, Field(description="The business metric being measured")]
    feedback_source: Annotated[FeedbackSource, Field(description="Source of the performance data")]
    status: Annotated[Status, Field(description="Processing status of the performance feedback")]
    submitted_at: Annotated[AwareDatetime, Field(description="ISO 8601 timestamp when feedback was submitted")]
    applied_at: Annotated[
        AwareDatetime | None,
        Field(description="ISO 8601 timestamp when feedback was applied to optimization algorithms"),
    ] = None
