# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_promoted-products_json.json
#   source_etag: W/"68ff4038-85f"
#   source_last_modified: Mon, 27 Oct 2025 09:49:44 GMT

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class PromotedProducts(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    manifest_skus: Annotated[
        list[str] | None, Field(description="Direct product SKU references from the brand manifest product catalog")
    ] = None
    manifest_tags: Annotated[
        list[str] | None,
        Field(
            description="Select products by tags from the brand manifest product catalog (e.g., 'organic', 'sauces', 'holiday')"
        ),
    ] = None
    manifest_category: Annotated[
        str | None,
        Field(
            description="Select products from a specific category in the brand manifest product catalog (e.g., 'beverages/soft-drinks', 'food/sauces')"
        ),
    ] = None
    manifest_query: Annotated[
        str | None,
        Field(
            description="Natural language query to select products from the brand manifest (e.g., 'all Kraft Heinz pasta sauces', 'organic products under $20')"
        ),
    ] = None
