# generated by datamodel-codegen:
#   filename:  _schemas_v1_media-buy_provide-performance-feedback-response_json.json
#   source_etag: W/"68ff4038-2e1"
#   source_last_modified: Mon, 27 Oct 2025 09:49:44 GMT

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(description="Error code for programmatic handling")]
    message: Annotated[str, Field(description="Human-readable error message")]
    field: Annotated[
        str | None, Field(description="Field path associated with the error (e.g., 'packages[0].targeting')")
    ] = None
    suggestion: Annotated[str | None, Field(description="Suggested fix for the error")] = None
    retry_after: Annotated[float | None, Field(description="Seconds to wait before retrying the operation", ge=0.0)] = (
        None
    )
    details: Annotated[Any | None, Field(description="Additional task-specific error details")] = None


class ProvidePerformanceFeedbackResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    success: Annotated[bool, Field(description="Whether the performance feedback was successfully received")]
    errors: Annotated[
        list[Error] | None,
        Field(
            description="Task-specific errors and warnings (e.g., invalid measurement period, missing campaign data)"
        ),
    ] = None
