# generated by datamodel-codegen:
#   filename:  _schemas_v1_signals_get-signals-response_json.json
#   source_etag: W/"68ff4038-1018"
#   source_last_modified: Mon, 27 Oct 2025 09:49:44 GMT

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class SignalType(Enum):
    marketplace = "marketplace"
    custom = "custom"
    owned = "owned"


class Scope(Enum):
    platform_wide = "platform-wide"
    account_specific = "account-specific"


class Deployment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: Annotated[str, Field(description="Platform name")]
    account: Annotated[str | None, Field(description="Specific account if applicable")] = None
    is_live: Annotated[bool, Field(description="Whether signal is currently active")]
    scope: Annotated[Scope, Field(description="Deployment scope")]
    decisioning_platform_segment_id: Annotated[str | None, Field(description="Platform-specific segment ID")] = None
    estimated_activation_duration_minutes: Annotated[
        float | None, Field(description="Time to activate if not live", ge=0.0)
    ] = None


class Pricing(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cpm: Annotated[float, Field(description="Cost per thousand impressions", ge=0.0)]
    currency: Annotated[str, Field(description="Currency code", pattern="^[A-Z]{3}$")]


class Signal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    signal_agent_segment_id: Annotated[str, Field(description="Unique identifier for the signal")]
    name: Annotated[str, Field(description="Human-readable signal name")]
    description: Annotated[str, Field(description="Detailed signal description")]
    signal_type: Annotated[SignalType, Field(description="Type of signal")]
    data_provider: Annotated[str, Field(description="Name of the data provider")]
    coverage_percentage: Annotated[float, Field(description="Percentage of audience coverage", ge=0.0, le=100.0)]
    deployments: Annotated[list[Deployment], Field(description="Array of platform deployments")]
    pricing: Annotated[Pricing, Field(description="Pricing information")]


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(description="Error code for programmatic handling")]
    message: Annotated[str, Field(description="Human-readable error message")]
    field: Annotated[
        str | None, Field(description="Field path associated with the error (e.g., 'packages[0].targeting')")
    ] = None
    suggestion: Annotated[str | None, Field(description="Suggested fix for the error")] = None
    retry_after: Annotated[float | None, Field(description="Seconds to wait before retrying the operation", ge=0.0)] = (
        None
    )
    details: Annotated[Any | None, Field(description="Additional task-specific error details")] = None


class GetSignalsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    signals: Annotated[list[Signal], Field(description="Array of matching signals")]
    errors: Annotated[
        list[Error] | None,
        Field(description="Task-specific errors and warnings (e.g., signal discovery or pricing issues)"),
    ] = None
