# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_creative-status_json.json
#   source_etag: W/"68ff4038-237"
#   source_last_modified: Mon, 27 Oct 2025 09:49:44 GMT

from __future__ import annotations

from enum import Enum


class CreativeStatus(Enum):
    processing = "processing"
    approved = "approved"
    rejected = "rejected"
    pending_review = "pending_review"
