# generated by datamodel-codegen:
#   filename:  _schemas_v1_media-buy_update-media-buy-response_json.json
#   source_etag: W/"68ff4038-640"
#   source_last_modified: Mon, 27 Oct 2025 09:49:44 GMT

from __future__ import annotations

from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class AffectedPackage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    package_id: Annotated[str, Field(description="Publisher's package identifier")]
    buyer_ref: Annotated[str, Field(description="Buyer's reference for the package")]


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(description="Error code for programmatic handling")]
    message: Annotated[str, Field(description="Human-readable error message")]
    field: Annotated[
        str | None, Field(description="Field path associated with the error (e.g., 'packages[0].targeting')")
    ] = None
    suggestion: Annotated[str | None, Field(description="Suggested fix for the error")] = None
    retry_after: Annotated[float | None, Field(description="Seconds to wait before retrying the operation", ge=0.0)] = (
        None
    )
    details: Annotated[Any | None, Field(description="Additional task-specific error details")] = None


class UpdateMediaBuyResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    media_buy_id: Annotated[str, Field(description="Publisher's identifier for the media buy")]
    buyer_ref: Annotated[str, Field(description="Buyer's reference identifier for the media buy")]
    implementation_date: Annotated[
        AwareDatetime | None,
        Field(description="ISO 8601 timestamp when changes take effect (null if pending approval)"),
    ] = None
    affected_packages: Annotated[
        list[AffectedPackage] | None, Field(description="Array of packages that were modified")
    ] = None
    errors: Annotated[
        list[Error] | None, Field(description="Task-specific errors and warnings (e.g., partial update failures)")
    ] = None
