# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_frequency-cap-scope_json.json
#   source_etag: W/"68ff4038-14d"
#   source_last_modified: Mon, 27 Oct 2025 09:49:44 GMT

from __future__ import annotations

from enum import Enum


class FrequencyCapScope(Enum):
    package = "package"
