# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_delivery-type_json.json
#   source_etag: W/"68ff4038-1a0"
#   source_last_modified: Mon, 27 Oct 2025 09:49:44 GMT

from __future__ import annotations

from enum import Enum


class DeliveryType(Enum):
    guaranteed = "guaranteed"
    non_guaranteed = "non_guaranteed"
