# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_publisher-identifier-types_json.json
#   source_etag: W/"68ff4038-19b"
#   source_last_modified: Mon, 27 Oct 2025 09:49:44 GMT

from __future__ import annotations

from enum import Enum


class PublisherIdentifierTypes(Enum):
    tag_id = "tag_id"
    duns = "duns"
    lei = "lei"
    seller_id = "seller_id"
    gln = "gln"
