# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_media-buy-status_json.json
#   source_etag: W/"68ff4038-203"
#   source_last_modified: Mon, 27 Oct 2025 09:49:44 GMT

from __future__ import annotations

from enum import Enum


class MediaBuyStatus(Enum):
    pending_activation = "pending_activation"
    active = "active"
    paused = "paused"
    completed = "completed"
