# generated by datamodel-codegen:
#   filename:  _schemas_v1_media-buy_list-authorized-properties-request_json.json
#   source_etag: W/"68ff4038-321"
#   source_last_modified: Mon, 27 Oct 2025 09:49:44 GMT

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class PublisherDomain(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Publisher domain to filter by (e.g., 'cnn.com', 'espn.com')",
            pattern="^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$",
        ),
    ]


class ListAuthorizedPropertiesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    publisher_domains: Annotated[
        list[PublisherDomain] | None,
        Field(
            description="Filter to specific publisher domains (optional). If omitted, returns all publishers this agent represents.",
            min_length=1,
        ),
    ] = None
