# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_package-status_json.json
#   source_etag: W/"68ff4038-1c4"
#   source_last_modified: Mon, 27 Oct 2025 09:49:44 GMT

from __future__ import annotations

from enum import Enum


class PackageStatus(Enum):
    draft = "draft"
    active = "active"
    paused = "paused"
    completed = "completed"
