# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_identifier-types_json.json
#   source_etag: W/"68ff4038-2fa"
#   source_last_modified: Mon, 27 Oct 2025 09:49:44 GMT

from __future__ import annotations

from enum import Enum


class PropertyIdentifierTypes(Enum):
    domain = "domain"
    subdomain = "subdomain"
    network_id = "network_id"
    ios_bundle = "ios_bundle"
    android_package = "android_package"
    apple_app_store_id = "apple_app_store_id"
    google_play_id = "google_play_id"
    roku_store_id = "roku_store_id"
    fire_tv_asin = "fire_tv_asin"
    samsung_app_id = "samsung_app_id"
    apple_tv_bundle = "apple_tv_bundle"
    bundle_id = "bundle_id"
    venue_id = "venue_id"
    screen_id = "screen_id"
    openooh_venue_type = "openooh_venue_type"
    rss_url = "rss_url"
    apple_podcast_id = "apple_podcast_id"
    spotify_show_id = "spotify_show_id"
    podcast_guid = "podcast_guid"
