# generated by datamodel-codegen:
#   filename:  _schemas_v1_signals_activate-signal-response_json.json
#   source_etag: W/"68ff4038-3db"
#   source_last_modified: Mon, 27 Oct 2025 09:49:44 GMT

from __future__ import annotations

from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(description="Error code for programmatic handling")]
    message: Annotated[str, Field(description="Human-readable error message")]
    field: Annotated[
        str | None, Field(description="Field path associated with the error (e.g., 'packages[0].targeting')")
    ] = None
    suggestion: Annotated[str | None, Field(description="Suggested fix for the error")] = None
    retry_after: Annotated[float | None, Field(description="Seconds to wait before retrying the operation", ge=0.0)] = (
        None
    )
    details: Annotated[Any | None, Field(description="Additional task-specific error details")] = None


class ActivateSignalResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    decisioning_platform_segment_id: Annotated[
        str | None, Field(description="The platform-specific ID to use once activated")
    ] = None
    estimated_activation_duration_minutes: Annotated[
        float | None, Field(description="Estimated time to complete (optional)", ge=0.0)
    ] = None
    deployed_at: Annotated[
        AwareDatetime | None, Field(description="Timestamp when activation completed (optional)")
    ] = None
    errors: Annotated[
        list[Error] | None,
        Field(description="Task-specific errors and warnings (e.g., activation failures, platform issues)"),
    ] = None
